version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: 'kanban-app'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres
    environment:
      POSTGRES_DB: 'test-kanban-app'
      POSTGRES_USER: 'test-postgres'
      POSTGRES_PASSWORD: 'test-postgres'
    ports:
      - '5433:5432' # Expose test db on a different port
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
